---

base_locale: en
locales: [en]

ignore_unused:
  - "decidim.components.half_signup.name"

ignore_missing:
  - decidim.participatory_processes.scopes.global
  - Decidim::Verifications::Sms::ExampleGateway
